<?php

 /** @var $block \Magento\Customer\Block\Account\Dashboard\Info */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php echo $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?php echo $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?php echo $block->escapeHtml($block->getName()) ?><br>
                    <?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                    <?php $_father = $block->getLayout()->createBlock(\TrainingDevendra\CustomerAccount\Block\Widget\FatherName::class) ?>
                    <?php $_mother = $block->getLayout()->createBlock(\TrainingDevendra\CustomerAccount\Block\Widget\MotherName::class) ?>
                    <?php if ($_mother->isEnabled()) : ?>
                        <?php $motherAttribute = $block->getCustomer()->getCustomAttribute('mother_name'); ?>
                        <?php if ($motherAttribute): ?>
                            <?php echo $motherAttribute->getValue(); ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($_father->isEnabled()) : ?>
                        <?php $fatherAttribute = $block->getCustomer()->getCustomAttribute('father_name'); ?>
                        <?php if ($fatherAttribute): ?>
                            <?php echo $fatherAttribute->getValue(); ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?php echo $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?php echo $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?php echo $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?php echo $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?php echo $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?php echo $block->escapeHtml(__('You subscribe to "General Subscription".')) ?>
                        <?php else: ?>
                            <?php echo $block->escapeHtml(__('You don\'t subscribe to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $block->getChildHtml('customer.account.dashboard.info.extra')?>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?php echo $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?php echo $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
