<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components": {
                    "exampleUiComponent":{
                        "component":"uiComponent",
                        "template": "Mytest_CustomAdmin/info",
                        "children":{
                            "child1":{
                                    "component":"uiComponent",
                                    "template": "Mytest_CustomAdmin/info",
                                    "children":{
                                        "child2":{
                                                "component":"uiComponent",
                                                "template": "Mytest_CustomAdmin/info"
                                        }
                                    }
                            }
                        }
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'exampleUiComponent'">
    <div data-bind="template: getTemplate()"></div>
</div>

<div class="callfor-popup">
    <h2>Simple Modal</h2>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            var modaloption = {
                type: 'popup',
                modalClass: 'modal-popup',
                responsive: true,
                innerScroll: true,
                clickableOverlay: true,
                title: 'Simple Modal'
            };
            var callforoption = modal(modaloption, $('.callfor-popup'));
            $('.callfor-popup').modal('openModal');
        }
    );
</script>