<?php


namespace Mytest\CustomAdmin\Controller\Adminhtml\Member;
use Magento\Backend\App\Action;
use Magento\Backend\Model\View\Result\RedirectFactory;
use Magento\Framework\App\ResponseInterface;
use Mytest\CustomAdmin\Model\AffiliateMember;

class Delete extends Action
{
    protected $model;
    protected $redirectFactory;

    public function __construct(
        RedirectFactory $redirectFactory,
        AffiliateMember $affiliateMember,
        Action\Context $context)
    {
        $this->redirectFactory=$redirectFactory;
        $this->model=$affiliateMember;
        parent::__construct($context);
    }


    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Mytest_CustomAdmin::parent');
        // TODO: Change the autogenerated stub

    }

    /**
     * Execute action based on request and return result
     *
     * Note: Request will be added as operation argument in future
     *
     * @return \Magento\Framework\Controller\ResultInterface|ResponseInterface
     * @throws \Exception
     */
    public function execute()
    {
        $resultRedirect = $this->redirectFactory->create();

        $id =$this->getRequest()->getParam('id');
        if($id)
        {
            $model=$this->model;
            $model->load($id);
            try{
                $model->delete();
                $this->messageManager->addSuccessMessage('Member Deleted successfully');
                return $resultRedirect->setPath('*/*/index');
            }
            catch(\Exception $e)
            {
                $this->messageManager->addErrorMessage($e->getMessage());
                return $resultRedirect->setPath('*/*/edit', ['id' =>$id]);
            }

        }

    }

}