<?php


namespace Mytest\CustomAdmin\Controller\Adminhtml\Member;


use Magento\Backend\App\Action;
use Magento\Framework\App\ResponseInterface;
use Magento\Backend\Model\View\Result\ForwardFactory;

class NewAction extends Action
{
    protected $forwardFactory;

    public function __construct(
        ForwardFactory $forwardFactory,
        Action\Context $context)
    {
        $this->forwardFactory=$forwardFactory;
        parent::__construct($context);
    }



    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Mytest_CustomAdmin::parent');
        // TODO: Change the autogenerated stub

    }

    /**
     * Execute action based on request and return result
     *
     * Note: Request will be added as operation argument in future
     *
     * @return \Magento\Framework\Controller\ResultInterface|ResponseInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function execute()
    {
        // TODO: Implement execute() method.
        $resultForward=$this->forwardFactory->create();
        return $resultForward->forward('Edit');
    }
}